# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2f6ee29edbc86a28dde3df651d718ad385e33c7f9e03edc39dff5da87ac3e3d51edb1254686c675ab055d3866ea24653d4374da344fcc7a440f124c804c1437

test:
  secret_key_base: 5e59384a35e893c829902f899f1f957b6c4cf24377e1a9dfac7cb8bd655c2cc8a92405409cb1a1fa01f0112db42cd059ef47b9f3f398b2d5bc0cf3dcddd4ef40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
